#!/bin/bash

die() { echo $1; exit 1; }

test -z "$1" && die "Usage: $(basename $0) <csvfile>"

infile=$1
test -r $infile || die "Cannot read $infile"

outfile=${infile%.csv}.pdf
test -e $outfile && die "Output file $outfile already exists"

jarfile=$(dirname $(readlink -f $0))/kp2html.jar
test -f $jarfile || die "Cannot read $jarfile"

echo -n "Password: "
read -s password
echo
echo -n "  Verify: "
read -s verify
echo
test "$password" != "$verify" && echo "Mismatch!" && exit 1

tmp=$(mktemp /tmp/$(basename $0).XXXXXX)
java -jar $jarfile $infile | wkhtmltopdf - $tmp && qpdf --encrypt $password $password 256 -- $tmp $outfile
rm -f $tmp
