#!/bin/bash

die() { echo $1; exit 1; }

test -z "$1" -o -z "$2" && die "Usage: $(basename $0) <infile> <outfile>"

infile=$1
outfile=$2
test -r $infile || die "Cannot read $infile"

jarfile=$(dirname $(readlink -f $0))/kp2html.jar
test -f $jarfile || die "Cannot read $jarfile"

echo -n "Password: "
read -s password
echo
echo -n "  Verify: "
read -s verify
echo
test "$password" != "$verify" && echo "Mismatch!" && exit 1

tmp=$(mktemp /tmp/$(basename $0).XXXXXX)
java -jar $jarfile $infile | wkhtmltopdf - $tmp && qpdf --encrypt $password $password 256 -- $tmp $outfile
rm -f $tmp
